// Generated by CoffeeScript 1.6.3
(function() {
  app.controller('HowToCtrl', function($scope, $location) {
    return $scope.homepage = function() {
      return $location.path("/");
    };
  });

}).call(this);
