// Generated by CoffeeScript 1.6.3
(function() {
  app.controller('RandomCtrl', function($scope, $location, $timeout) {
    var fbRef, gameId, numRef;
    localStorage.removeItem('player');
    localStorage.removeItem('waiting');
    localStorage.removeItem('starting');
    numRef = new Firebase('https://3t.firebaseio.com/');
    numRef.on('value', function(data) {
      return $scope.$apply(function() {
        var k, v;
        return $scope.num_games = ((function() {
          var _ref, _results;
          _ref = data.val();
          _results = [];
          for (k in _ref) {
            v = _ref[k];
            _results.push(k);
          }
          return _results;
        })()).length * 2;
      });
    });
    $scope.homepage = function() {
      fbRef.off('value');
      fbRef.set(null);
      return $location.path("/");
    };
    if (!gameId) {
      gameId = 0;
    }
    fbRef = new Firebase('https://3t.firebaseio.com/random');
    return fbRef.on('value', function(x) {
      if (x.val() && !localStorage.waiting) {
        console.log('Second person connected');
        localStorage.starting = true;
        $location.path("/" + (x.val()));
        $scope.$apply();
        localStorage.removeItem('waiting');
        fbRef.off('value');
        return fbRef.set(null);
      } else {
        if (!localStorage.waiting) {
          console.log('First person connected');
          localStorage.waiting = true;
          gameId = Math.floor(Math.random() * 99999);
          fbRef.onDisconnect().set(null);
          return fbRef.set(gameId);
        } else {
          if (x.val()) {
            return console.log("First person set gameId to " + gameId);
          } else {
            console.log("Match found! Let the games begin!");
            localStorage.removeItem('waiting');
            fbRef.off('value');
            return $timeout(function() {
              return $location.path("/" + gameId);
            }, 1500, true);
          }
        }
      }
    });
  });

}).call(this);
