// Generated by CoffeeScript 1.6.3
(function() {
  app.controller('SplashCtrl', function($scope, $location) {
    localStorage.removeItem('player');
    $scope.newOnlineGame = function() {
      console.log('Creating new online game');
      localStorage.player = 1;
      return $location.path("/" + (Math.floor(Math.random() * 78343)));
    };
    $scope.newLocalGame = function() {
      console.log('Creating local game');
      return $location.path("/local");
    };
    return $scope.howToPlay = function() {
      return $location.path("/howto");
    };
  });

}).call(this);
